'use strict';
// No network dependencies. All case-study images are extracted from the supplied brief.
const imageNames=['01_research_big','02_research_small','03_notebooklm_sources','04_notebooklm_infographic','05_notebooklm_video','06_service_map_select','07_service_progress','08_service_uds','09_service_pzz','10_makeev_rhino','11_qgis_agent','12_urban_street','13_comfyui','14_claude_video_1','15_claude_video_2','16_claude_video_3','17_tool_video','18_revit_agent','19_nano_banana','20_astra_church'];
const imagePath=n=>`assets/images/${imageNames[n-1]}.png`;
const groups=['Вступление','Искать и исследовать','Своя база знаний','Агенты и инструменты','Создавать результат','Вывод'];
const colors=['#22d3ee','#22d3ee','#2dd4bf','#a78bfa','#7db6ff','#22d3ee'];
const slideData=[
 {title:'ИИ в Граданализе',type:'hero',g:0},
 {title:'Один специалист — цифровая команда',type:'team',g:0},
 {title:'Четыре направления',type:'directions',g:0},
 {title:'Как менялся анализ',type:'flow',g:1,nodes:['Бумажные карты','Интернет','GIS','ИИ'],notes:['Архивы · геодезия','Доступ к информации','Пространственные данные','Исследование и действия']},
 {title:'Проблема уже не в отсутствии информации',type:'compare',g:1},
 {title:'Большая исследовательская задача',type:'media',g:1,img:1,layout:'portrait',aside:'metrics',caption:'Исследование типологии и технологического процесса'},
 {title:'Это уже не просто поисковик',type:'roles',g:1},
 {title:'Точечный вопрос вместо отдельного поиска',type:'media',g:1,img:2,layout:'portrait',steps:['Вопрос','Норматив','Пункт','Решение'],caption:'ГОСТ / практический вывод для Revit'},
 {title:'Не весь интернет',type:'filter',g:2},
 {title:'NotebookLM: своя нормативная база',type:'media',g:2,img:3,focus:true,caption:'Источники → вопрос → ответ → цитата'},
 {title:'ИИ находит — специалист проверяет',type:'statement',g:2,html:'ИИ находит ответ.<br><em>Специалист проверяет<br>источник.</em>'},
 {title:'Незнакомая нормативная система',type:'flow',g:2,nodes:['Специалист','Документы','Вопрос','Ответ + источник'],notes:['Из другой страны','На русском языке','На своём языке','Оригинальный документ']},
 {title:'Из СП — в понятную инфографику',type:'media',g:2,img:4,caption:'Пример автоматической инфографики по СП 42.13330.2016'},
 {title:'Из той же базы — видео, карточки, тесты',type:'media',g:2,img:5,layout:'video',caption:'Кадр видеопересказа «Безопасный маршрут»',tags:['Презентация','Аудио','Ментальная карта','Карточки','Тест','Таблица']},
 {title:'От чата — к агенту',type:'agent',g:3},
 {title:'Агент работает в QGIS',type:'media',g:3,img:11,caption:'Текстовая задача → зоны доступности остановок → изменения в проекте QGIS',focus:'qgis'},
 {title:'Создавать программу под свою работу',type:'custom',g:3},
 {title:'Эксперимент: участок → 10 схем',type:'carousel',g:3,images:[6,7,8,9],labels:['Выделение участка','Анализ готов','Схема УДС','ПЗЗ и регламенты'],caption:'Собственный сервис предпроектного анализа'},
 {title:'Архитекторы уже делают свой софт',type:'media',g:3,img:10,layout:'side',steps:['Редактируемо','Дороги улучшены','Для моделирования'],caption:'Makeev Architect / городская геометрия в Rhino + Grasshopper'},
 {title:'Узкий сервис под конкретную задачу',type:'media',g:3,img:12,caption:'urban:STREET / конструирование профиля улицы',focus:'street'},
 {title:'То же самое внутри BIM',type:'flow',g:3,nodes:['Операция','Правила','Coding-agent','Revit tool','Excel'],notes:['Ручная работа','Зонирование · ТЭП','Автоматизация','Свой плагин','Выгрузка']},
 {title:'От данных к понятной форме',type:'flow',g:4,nodes:['Данные','Анализ','Схема','Модель','Визуализация','Презентация']},
 {title:'Генеративный визуал',type:'media',g:4,img:13,caption:'ComfyUI / управляемая генерация архитектурного образа'},
 {title:'Из проекта — в визуальную историю',type:'carousel',g:4,images:[14,15,16],labels:['Территория','Архитектурное решение','Ночной сценарий'],caption:'Claude / кадры видеопрезентации проекта'},
 {title:'ИИ объясняет работу инструмента',type:'media',g:4,img:17,caption:'WFC Facade Constructor / модульная логика инструмента'},
 {title:'Агент участвует в моделировании',type:'media',g:4,img:18,caption:'Анализирует · сравнивает · исправляет · создаёт модель',focus:'revit'},
 {title:'Техническая модель → подача',type:'media',g:4,img:19,caption:'Nano Banana / из модели или скриншота — в презентационный образ'},
 {title:'ИИ создаёт 3D-геометрию',type:'media',g:4,img:20,layout:'portrait',steps:['Фото / источники','Облачное моделирование','3DM','Revit'],caption:'Кейс из материалов автора / GPT-6 Astra · модель церкви'},
 {title:'Что уже можно передать ИИ',type:'summary',g:5},
 {title:'Маленькая команда — возможности большой',type:'team',g:5},
 {title:'Финальный тезис',type:'final',g:5}
];
const pad=n=>String(n).padStart(2,'0');
const flow=(nodes,notes=[])=>`<div class="flow">${nodes.map((n,i)=>`<div class="flow-node" tabindex="0"><span class="step-num">${pad(i+1)}</span><strong>${n}</strong>${notes[i]?`<small>${notes[i]}</small>`:''}</div>`).join('')}</div>`;
function cluster(final=false,roles=false){
 const labels=roles?['Поиск','Чтение','Перевод','Сравнение','Анализ','Структурирование']:final?['Исследование','Код','GIS','Визуал','Автоматизация']:['Исследователь','Аналитик','Разработчик','Визуализатор','Ассистент'];
 const positions=roles?[[290,75],[700,35],[1110,75],[1110,300],[700,345],[290,300]]:[[600,60],[1000,65],[1230,205],[970,345],[585,325]];
 const cx=roles?700:225,cy=195;
 return `<div class="cluster"><svg viewBox="0 0 1400 400" role="img" aria-label="${roles?'ИИ объединяет шесть функций':'Специалист задаёт направление цифровой команде'}"><circle cx="${cx}" cy="${cy}" r="83"/><circle cx="${cx}" cy="${cy}" r="96" style="fill:none;stroke-opacity:.16"/><text x="${cx}" y="${cy+5}" class="center-label">${roles?'ИИ':'Человек'}</text><text x="${cx}" y="${cy+33}" class="small-label">${roles?'ОДНА LLM':'НАПРАВЛЕНИЕ'}</text>${positions.map(([x,y],i)=>`<path d="M${cx+(!roles?83:0)},${cy} Q${(cx+x)/2},${cy} ${x},${y}"/><path class="signal" style="animation-delay:-${i*2}s" d="M${cx+(!roles?83:0)},${cy} Q${(cx+x)/2},${cy} ${x},${y}"/><g class="role"><circle cx="${x}" cy="${y}" r="8"/><text x="${x}" y="${y+36}">${labels[i]}</text></g>`).join('')}</svg></div>`;
}
function directions(summary=false){const names=summary?['Исследовать','Знать','Действовать','Создавать']:['Искать и<br>исследовать','Работать со своей<br>базой знаний','Анализировать и<br>автоматизировать','Создавать и<br>представлять'];const details=summary?['Искать · сравнивать<br>Структурировать','Читать · находить<br>Проверять источник','Анализировать<br>Автоматизировать','Моделировать<br>Визуализировать']:['Вопросы и источники','Документы, которым доверяем','Агенты и свои инструменты','Модели и визуальные истории'];return `<div class="directions">${names.map((n,i)=>`<button class="direction" data-goto="${[4,9,15,22][i]}" style="--c:${['#22d3ee','#2dd4bf','#a78bfa','#7db6ff'][i]}"><span class="num">${pad(i+1)}</span><strong>${n}</strong><small>${details[i]}</small><span class="range">${['04 — 08','09 — 14','15 — 21','22 — 28'][i]}</span></button>`).join('')}</div>`}
function picture(n,caption,extra=''){return `<button class="media-window" aria-label="Увеличить: ${caption}" data-image="${n}"><img data-src="${imagePath(n)}" alt="${caption}" decoding="async"><span class="zoom-hint">Увеличить ↗</span>${extra}</button>`}
function media(d){
 let aside=d.aside==='metrics'?'<div class="media-aside"><div class="metric"><b>17</b><span>минут</span></div><div class="metric"><b>18</b><span>страниц</span></div><div class="metric"><b>38</b><span>источников</span></div></div>':d.steps?`<div class="media-aside"><div class="vertical-steps">${d.steps.map(s=>`<span>${s}</span>`).join('')}</div></div>`:'';
 if(d.layout==='video')aside=`<div class="media-aside"><h3>«Безопасный маршрут»</h3><p class="subtitle">Одна база документов.<br>Разные форматы.</p><div class="tags">${d.tags.map(t=>`<span>${t}</span>`).join('')}</div></div>`;
 const pic=picture(d.img,d.caption,d.focus?'<span class="spotlight"><span class="spotlight-tag"></span></span>':'');
 const focusLabels=d.focus===true?['Источники','Вопрос','Цитата']:d.focus==='qgis'?['Карта','Диалог']:d.focus==='street'?['Профиль улицы','Параметры']:['Revit-модель'];
 return `<div class="media-content ${d.layout==='portrait'?'side portrait':d.layout==='side'?'side':''}">${d.layout==='video'?pic+aside:aside+pic}</div>${d.focus?`<div class="focus-tabs" aria-label="Выделить часть скриншота"><button data-focus="-1" aria-pressed="true">Весь экран</button>${focusLabels.map((s,i)=>`<button data-focus="${i}" aria-pressed="false">${s}</button>`).join('')}</div>`:''}<p class="caption">${d.caption}</p>`;
}
function content(d,i){switch(d.type){
 case 'hero':return `<div class="hero-mark" aria-hidden="true">ИИ</div><div class="index-line"></div><p class="eyebrow">СПбГАСУ / ЦИФРОВАЯ ПРАКТИКА</p><h1>ИИ в<span>Граданализе</span></h1><p class="subtitle">От поиска информации и сбора данных —<br>к автоматизации и собственным инструментам</p><div class="hero-bottom"><button class="primary" data-goto="2">Начать лекцию</button><span class="hint">← → &nbsp; / &nbsp; ПРОБЕЛ &nbsp; / &nbsp; КОЛЕСО</span></div>`;
 case 'team':return `<h2>${i===1?'Один специалист —<br><em>цифровая команда</em>':'Маленькая команда —<br><em>возможности большой</em>'}</h2>${cluster(i===29)}`;
 case 'directions':return `<h2>Четыре направления</h2>${directions()}`;
 case 'summary':return `<h2>${d.title}</h2>${directions(true)}`;
 case 'flow':return `<h2>${d.title}</h2>${flow(d.nodes,d.notes)}`;
 case 'compare':return `<h2>Меньше времени на поиск.<br><em>Больше — на понимание результата.</em></h2><div class="comparison"><div><h3>Человек</h3><div class="docs">${'<i></i>'.repeat(7)}</div><p>Документы по одному</p></div><div><h3>Человек + ИИ</h3><div class="docs many">${Array.from({length:36},(_,n)=>`<i style="--i:${n}"></i>`).join('')}</div><p>PDF · сайты · карты</p></div></div>`;
 case 'roles':return `<h2>${d.title}</h2>${cluster(false,true)}`;
 case 'filter':return `<h2 class="statement small">Что если нам не нужен<br>весь интернет, а только<br><em>документы, которым мы доверяем?</em></h2><div class="filter-visual"><div class="cloud"><span>Сайты</span><span>Статьи</span><span>Интернет</span><span>Форумы</span><span>Архивы</span><span>PDF</span></div><div class="funnel" aria-hidden="true">›</div><div class="trusted"><span>СП</span><span>ГОСТ</span><span>Методики</span></div></div>`;
 case 'statement':return `<div class="quote-line"></div><h2 class="statement">${d.html}</h2><span class="large-number" aria-hidden="true">§</span>`;
 case 'agent':return `<h2>От чата — <em>к агенту</em></h2><div class="agent-compare"><div><h3>ЧАТ</h3>${flow(['Вопрос','Ответ'])}</div><div><h3>АГЕНТ</h3>${flow(['Задача','Действие','Результат'])}</div></div>`;
 case 'custom':return `<h2 class="statement small"><span class="dim">Не подстраивать работу<br>под программу —</span><br><em>создавать программу<br>под свою работу.</em></h2>${flow(['Задача','Логика','Coding-agent','Инструмент'])}`;
 case 'media':return `<div><p class="eyebrow">${groups[d.g]}</p><h2>${d.title}</h2></div>${media(d)}`;
 case 'carousel':return `<div><p class="eyebrow">${groups[d.g]}</p><h2>${d.title}</h2></div><div class="carousel-wrap">${picture(d.images[0],d.labels[0])}<div class="carousel-controls">${d.labels.map((s,j)=>`<button data-frame="${j}" aria-pressed="${j===0}">${pad(j+1)} / ${s}</button>`).join('')}<button class="play" aria-label="Автосмена кадров" aria-pressed="false">Авто ▶</button></div></div><p class="caption">${d.caption}</p>`;
 case 'final':return `<div class="quote-line"></div><h2 class="statement">ИИ не заменяет<br>градостроительный анализ.<br><em>Он сокращает расстояние<br>между вопросом<br>и профессиональным решением.</em></h2><p class="subtitle">Специалист всё больше занимается постановкой задач,<br>выбором решений и проверкой результата.</p>`;
}}
const deck=document.querySelector('#deck');
deck.innerHTML=slideData.map((d,i)=>`<section id="slide-${pad(i+1)}" class="slide kind-${d.type} ${['hero','final'].includes(d.type)?d.type:''} ${['media','carousel'].includes(d.type)?'media-slide':''} ${d.layout==='video'?'portrait-video':''}" aria-label="${i+1}. ${d.title}" aria-hidden="true" inert style="--accent:${colors[d.g]}">${!['hero','media','carousel','final'].includes(d.type)?`<p class="eyebrow">${groups[d.g]}</p>`:''}${content(d,i)}</section>`).join('');
const slides=[...deck.children],overview=document.querySelector('#overview'),lightbox=document.querySelector('#lightbox');
document.querySelector('#overview-list').innerHTML=slideData.map((d,i)=>`<button data-goto="${i+1}"><span class="n">${pad(i+1)}</span><span><small>${groups[d.g]}</small><strong>${d.title}</strong></span></button>`).join('');
let current=-1,lockedUntil=0,carouselTimer=null,carouselFrame=0,autoPlaying=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let manualStill=false,autoStill=false;
function isStill(){return reduced.matches||manualStill||autoStill}
function loadImages(index){for(let k=Math.max(0,index-1);k<=Math.min(30,index+1);k++){slides[k].querySelectorAll('img[data-src]').forEach(img=>{if(!img.src)img.src=img.dataset.src});const data=slideData[k];if(data.images)data.images.forEach(n=>{const img=new Image();img.src=imagePath(n)})}}
function stopCarousel(){clearInterval(carouselTimer);carouselTimer=null;autoPlaying=false;document.querySelectorAll('.play').forEach(b=>{b.textContent='Авто ▶';b.setAttribute('aria-pressed','false')})}
function go(index,{historyMode='push',force=false}={}){if(index<0||index>30||index===current)return;if(!force&&performance.now()<lockedUntil)return;lockedUntil=performance.now()+560;stopCarousel();if(current>=0){slides[current].classList.remove('active');slides[current].setAttribute('aria-hidden','true');slides[current].inert=true}current=index;loadImages(index);const slide=slides[index];slide.inert=false;slide.setAttribute('aria-hidden','false');slide.classList.add('active');document.documentElement.style.setProperty('--accent',colors[slideData[index].g]);document.querySelector('#chapter').textContent=`${pad(index+1)} / ${groups[slideData[index].g]}`;document.querySelector('#counter').textContent=`${pad(index+1)} / 31`;document.querySelector('#progress').style.width=`${(index+1)/31*100}%`;document.querySelector('#prev').disabled=index===0;document.querySelector('#next').disabled=index===30;document.querySelector('#announcer').textContent=`Слайд ${index+1}: ${slideData[index].title}`;document.querySelectorAll('#overview-list button').forEach((b,j)=>b.setAttribute('aria-current',j===index?'true':'false'));const hash=`#slide-${pad(index+1)}`;if(location.hash!==hash){history[historyMode==='replace'?'replaceState':'pushState'](null,'',hash)}if(slideData[index].type==='carousel'){carouselFrame=0;setFrame(0)}document.title=`${pad(index+1)} · ${slideData[index].title} — ИИ в Граданализе`;if(isStill())drawCity(0)}
function fromHash(){const match=location.hash.match(/^#slide-(\d{2})$/);const target=match?Number(match[1])-1:0;go(Math.max(0,Math.min(30,target)),{historyMode:'replace',force:true})}
function navigate(delta){if(!overview.open&&!lightbox.open)go(current+delta)}
document.querySelector('#next').addEventListener('click',()=>navigate(1));document.querySelector('#prev').addEventListener('click',()=>navigate(-1));
document.addEventListener('click',e=>{const b=e.target.closest('[data-goto]');if(!b)return;const n=Number(b.dataset.goto)-1;if(overview.open)overview.close();go(n,{force:true});if(b.closest('#deck'))document.querySelector('#overview-open').focus()});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go(0,{force:true})});
document.querySelector('#overview-open').addEventListener('click',()=>{stopCarousel();overview.showModal();overview.querySelector('[aria-current=true]').focus()});
document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
document.addEventListener('keydown',e=>{if(overview.open||lightbox.open)return;if(e.altKey||e.ctrlKey||e.metaKey||e.target.matches('input,textarea,select'))return;if(e.code==='Space'&&e.target.closest('button,a'))return;let delta=0;if(['ArrowRight','PageDown'].includes(e.key)||e.code==='Space'&&!e.shiftKey)delta=1;if(['ArrowLeft','PageUp'].includes(e.key)||e.code==='Space'&&e.shiftKey)delta=-1;if(delta){e.preventDefault();if(!e.repeat)navigate(delta)}if(e.key==='Home'){e.preventDefault();go(0,{force:true})}if(e.key==='End'){e.preventDefault();go(30,{force:true})}if(e.key.toLowerCase()==='m')document.querySelector('#overview-open').click();if(e.key.toLowerCase()==='f')toggleFullscreen()});
let wheelTotal=0,wheelTime=0,wheelFired=false,wheelDirection=0;
document.addEventListener('wheel',e=>{if(overview.open||lightbox.open||e.ctrlKey)return;e.preventDefault();const now=performance.now();const raw=Math.abs(e.deltaY)>=Math.abs(e.deltaX)?e.deltaY:e.deltaX;const direction=Math.sign(raw);if(now-wheelTime>180||direction!==wheelDirection){wheelTotal=0;wheelFired=false}wheelTime=now;wheelDirection=direction;wheelTotal+=raw*(e.deltaMode===1?16:e.deltaMode===2?700:1);if(!wheelFired&&Math.abs(wheelTotal)>38){wheelFired=true;navigate(direction)}},{passive:false});
let touchStart=null;document.addEventListener('touchstart',e=>{if(e.touches.length===1)touchStart=[e.touches[0].clientX,e.touches[0].clientY]},{passive:true});document.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart[0],dy=e.changedTouches[0].clientY-touchStart[1];touchStart=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.3)navigate(dx<0?1:-1)},{passive:true});
window.addEventListener('hashchange',fromHash);window.addEventListener('popstate',fromHash);
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.querySelector('#announcer').textContent='Используйте F11 для полноэкранного режима'}}document.querySelector('#fullscreen').addEventListener('click',toggleFullscreen);
document.addEventListener('fullscreenchange',()=>{document.querySelector('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Выйти из полного экрана':'Полный экран')});
document.querySelector('#motion').addEventListener('click',()=>{manualStill=!manualStill;autoStill=false;syncMotion()});reduced.addEventListener('change',syncMotion);
function syncMotion(){document.body.classList.toggle('still',isStill());const b=document.querySelector('#motion');b.setAttribute('aria-pressed',String(isStill()));b.setAttribute('aria-label',isStill()?'Включить анимацию фона':'Отключить анимацию фона');if(isStill())stopCarousel();drawCity(0);startCity()}
function setFrame(n){const d=slideData[current];if(!d.images)return;carouselFrame=n;const slide=slides[current],img=slide.querySelector('.media-window img'),b=slide.querySelector('.media-window');img.src=imagePath(d.images[n]);img.alt=d.labels[n];b.dataset.image=d.images[n];b.setAttribute('aria-label',`Увеличить: ${d.labels[n]}`);slide.querySelectorAll('[data-frame]').forEach((el,j)=>el.setAttribute('aria-pressed',String(n===j)))}
document.addEventListener('click',e=>{const frame=e.target.closest('[data-frame]');if(frame){stopCarousel();setFrame(Number(frame.dataset.frame))}const play=e.target.closest('.play');if(play){if(autoPlaying)stopCarousel();else{autoPlaying=true;play.textContent='Пауза Ⅱ';play.setAttribute('aria-pressed','true');carouselTimer=setInterval(()=>{if(!document.hidden&&!lightbox.open&&!overview.open)setFrame((carouselFrame+1)%slideData[current].images.length)},2400)}}const pic=e.target.closest('.media-window');if(pic){stopCarousel();const img=lightbox.querySelector('img');img.src=imagePath(Number(pic.dataset.image));img.alt=pic.querySelector('img').alt;lightbox.querySelector('p').textContent=img.alt+' · Esc — закрыть';lightbox.showModal()}});
// Highlight coordinates are normalized against the uncropped image, never its container.
const focusAreas={notebook:[[.006,.06,.248,.93],[.325,.065,.355,.1],[.414,.353,.219,.45]],qgis:[[.22,.1,.27,.85],[.5,0,.5,.94]],street:[[.22,.13,.57,.72],[.84,.05,.16,.91]],revit:[[.62,0,.38,1]]};
function positionSpotlight(slide,choice){const box=slide.querySelector('.media-window'),img=box.querySelector('img'),spot=box.querySelector('.spotlight');if(choice<0){spot.classList.remove('on');return}const d=slideData[slides.indexOf(slide)],areas=focusAreas[d.focus===true?'notebook':d.focus],a=areas[choice];if(!a||!img.naturalWidth)return;const scale=Math.min(box.clientWidth/img.naturalWidth,box.clientHeight/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;spot.style.left=`${(box.clientWidth-w)/2+a[0]*w}px`;spot.style.top=`${(box.clientHeight-h)/2+a[1]*h}px`;spot.style.width=`${a[2]*w}px`;spot.style.height=`${a[3]*h}px`;spot.querySelector('span').textContent=slide.querySelector(`[data-focus="${choice}"]`).textContent;spot.classList.add('on')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-focus]');if(!b)return;const slide=b.closest('.slide'),choice=Number(b.dataset.focus);slide.querySelectorAll('[data-focus]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));positionSpotlight(slide,choice)});
function resize(){document.querySelector('#stage').style.setProperty('--scale',Math.min(innerWidth/1600,innerHeight/900));slides.forEach(s=>{const b=s.querySelector('[data-focus][aria-pressed=true]');if(b)positionSpotlight(s,Number(b.dataset.focus))})}window.addEventListener('resize',resize);
// Lightweight architectural field. A deterministic parcel grid, flowing contour lines,
// and slow paths are rendered at 30fps. Sustained slow frames trigger a static fallback.
const canvas=document.querySelector('#city'),ctx=canvas.getContext('2d');let pointer={x:0,y:0},smooth={x:0,y:0},raf=0,lastDraw=0,slowFrames=0,samples=0,totalTime=0;
const parcels=[];let seed=41;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};for(let y=-200;y<1200;y+=72){for(let x=-250;x<1850;x+=96){if(rand()>.18)parcels.push({x:x+8+rand()*7,y:y+8,w:45+rand()*25,h:32+rand()*19,fill:rand()>.87})}}
document.addEventListener('pointermove',e=>{if(isStill())return;pointer.x=(e.clientX/innerWidth-.5)*15;pointer.y=(e.clientY/innerHeight-.5)*12},{passive:true});
function drawCity(time){if(!ctx)return;const still=isStill()||current===30;const t=still?0:time*.00006;smooth.x+=(pointer.x-smooth.x)*.03;smooth.y+=(pointer.y-smooth.y)*.03;ctx.clearRect(0,0,1600,900);ctx.fillStyle='#0b0f15';ctx.fillRect(0,0,1600,900);const glow=(x,y,r,color)=>{const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,1600,900)};glow(1210+Math.sin(t)*40,360,600,'#22d3ee10');glow(950,760,460,'#8b5cf60c');glow(320,20,500,'#2dd4bf06');ctx.save();ctx.translate(800+(still?0:smooth.x),450+(still?0:smooth.y));ctx.rotate(-.24);ctx.transform(1,0,.2,.83,0,0);ctx.translate(-780,-450);ctx.strokeStyle='#6992ad14';ctx.lineWidth=.8;for(const p of parcels){ctx.strokeRect(p.x,p.y,p.w,p.h);if(p.fill){ctx.fillStyle='#22d3ee06';ctx.fillRect(p.x,p.y,p.w,p.h)}}ctx.strokeStyle='#22d3ee21';ctx.lineWidth=1;for(let k=0;k<8;k++){ctx.beginPath();for(let x=-200;x<1800;x+=12){const y=260+k*21+Math.sin(x*.003+t*.4+k*.08)*135+Math.sin(x*.007+k*.02)*34;x===-200?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke()}const paths=[[0,780,1600,100],[400,-100,1150,1000],[0,120,1600,740]];paths.forEach(([x1,y1,x2,y2],k)=>{ctx.strokeStyle=k===1?'#a78bfa1b':'#22d3ee20';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const f=(t*.12+k*.27)%1,x=x1+(x2-x1)*f,y=y1+(y2-y1)*f;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=k===1?'#a78bfa77':'#22d3ee88';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=15;ctx.fill();ctx.shadowBlur=0});ctx.restore()}
function animate(time){raf=0;if(document.hidden||isStill())return;if(time-lastDraw>=32){const delta=time-lastDraw;lastDraw=time;const start=performance.now();drawCity(time);totalTime+=performance.now()-start;samples++;if(delta>75&&delta<1000)slowFrames++;if(samples>=100){if(totalTime/samples>20||slowFrames>45){autoStill=true;syncMotion();return}samples=0;slowFrames=0;totalTime=0}}raf=requestAnimationFrame(animate)}
function startCity(){if(raf)cancelAnimationFrame(raf);raf=0;if(!isStill()&&!document.hidden){lastDraw=performance.now();raf=requestAnimationFrame(animate)}}document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else startCity()});
resize();fromHash();syncMotion();
